version: '3.8'

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge

services:
  backend:
    build: ./backend
    command: yarn run start
    environment:
      NODE_ENV: 'development'
      ORBITER_SCENE: maker # dashboard: only dashboard | maker: only maker service | all
      ORBITER_MAKER_PRIVATE_KEYS: '' # {"makerAddress":"private_key"}
      PROMETHEUS_ALERTMANAGER: '{"api":"http://alertmanager:9093"}' # {"api":"http://alertmanager:9093"}
      DB_HOST: db
      TELEGRAM_TOKEN: '${TELEGRAM_TOKEN}'
      CHAT_ID: '${CHAT_ID}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
      DB_NAME: '${DB_NAME}'
      logstashHost: '${logstashHost}'
      logstashPort: '${logstashPort}'
    volumes:
      - './backend/logs:/app/logs'
      - './backend/runtime:/app/runtime'

    #   - './backend:/app'
    ports:
      - '3002:3002'
    restart: always
    networks:
      - app-network

  db:
    image: mysql:5.7.16
    # image: ibex/debian-mysql-server-5.7
    # Set mysqld charset
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/conf.d:/etc/mysql/conf.d'
    ports:
      - '3307:3306'
    restart: always
    networks:
      - app-network
